# Chargé automatiquement par Docker Compose en développement
# Pour la prod : docker compose -f compose.yml up
services:
  api:
    build:
      target: dev
    volumes:
      - ./api:/app
      - api_static:/app/static

  front:
    build:
      target: dev
    volumes:
      - ./front/src:/app/src
